[tool.autopep8]
ignore = "E401,E402"
max_line_length = 88

[tool.pydocstyle]
convention = "google"
add_ignore = "D100"  # Missing docstring in public module

[tool.isort]
combine_as_imports = true
combine_star = true
multi_line_output = 3
force_grid_wrap = 2
lines_after_imports = 2
